// Importing Next.js metadata type
import type { Metadata } from "next";

// Importing fonts
import { Geist, Geist_Mono } from "next/font/google";

// Importing Redux Provider wrapper
import ReduxProvider from "./store/Provider";

// Importing global CSS
import "./globals.css";

// Setting font for the app
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Setting mono font
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for browser
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout wraps the entire app
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ReduxProvider makes store available to whole app */}
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
